version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    restart: unless-stopped